### ISSUE TITLE
Simulate different subfamilies, how to configure `rmsk_query` for that

### ISSUE THREAD

**Issue by mikecuoco** [gage-lab/bulk_te_bench#15]

**Comment by jjjoelle** [comment]
notes
- make_txome.py line 45 uses rmsk_query
- query is just bool subset of cols in df 

ideas: 
- we make pre-determined mapping of short cuts to queries (like L1 means query = "repName == 'L1HS' & length > 6000")
- it's a list of queries for rmsk and then they're concatenated together with no overlaps ( ["repName == 'L1HS' & length > 6000", "repName == 'L1PA6 & length > 6000"])
